
-- 13-1
--1 EMP 테이블과 같은 구조의 테이블 생성
CREATE TABLE EMPIDX
 AS SELECT * FROM EMP;

--2 EMPNO 열에 인덱스
CREATE INDEX IDX_EMPIDX_EMPNO 
    ON EMPIDX (EMPNO);
	     
--3
SELECT * 
  FROM USER_INDEXES 
 WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';

-- 13-2 : VIEW 권한 없음 => 시스템 계정
CREATE OR REPLACE VIEW EMPIDX_OVER15K 
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO, 
               SAL, NVL2(COMM, 'O', 'X') AS COMM 
          FROM EMPIDX 
         WHERE SAL > 1500); 
SELECT * FROM empidx_over15k;

-- 13-3
--1
CREATE TABLE DEPTSEQ
    AS SELECT * FROM DEPT; 
	
--2 
CREATE SEQUENCE SEQ_DEPTSEQ 
   INCREMENT BY 1
   START WITH 1
   MAXVALUE 99
   MINVALUE 1
   NOCYCLE NOCACHE;
   
--3
SELECT * FROM DEPTSEQ;
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'DATABASE', 'SEOUL');

INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN');

INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN');
